version: '3.7'
services:
  # Banco de dados
  concurrency-db:
    container_name: concurrency-db
    image: postgres:15
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 80M
    ports:
      - '5432:5432'
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=concurrency
      - TZ=America/Sao_Paulo
    volumes:
      - ./docker-bd/volume_postgres:/var/lib/postgresql/data
